name: Build and Test
on: push

jobs:
    test:
        runs-on: ubuntu-latest

        # services:
        #   postgres:
        #     image: postgres:latest
        #     env:
        #       POSTGRES_DB: chitter, chitter_test
        #       POSTGRES_USER: testuser
        #       POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
        #     ports:
        #       - 5432:5432
        #     options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

        steps:
            - name: Checks out the code
              uses: actions/checkout@v3

            - name: Install PostgreSQL
              run: |
                sudo apt update
                sudo apt install postgresql postgresql-client
            
            - name: Set up Python 3.12
              uses: actions/setup-python@v4
              with:
                python-version: 3.12.0

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install pipenv
                pipenv install --dev
                pipenv run playwright install
                pipenv run createdb chitter
                pipenv run createdb chitter_test
            
            - name: Test with pytest
              run: |
                pipenv run pytest