name: Build and Test
on: push

jobs:
    test:
        runs-on: ubuntu-latest

        services:
          postgres:
            image: postgres
            env:
              POSTGRES_PASSWORD: postgres
            options: >-
              --health-cmd pg_isready
              --health-interval 10s
              --health-timeout 5s
              --health-retries 5
            ports:
              - 5432:5432

        steps:
            - name: Checks out the code
              uses: actions/checkout@v3

            - name: Set up Python 3.12
              uses: actions/setup-python@v4
              with:
                python-version: 3.12.0

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install psycopg
                pip install pipenv
                pipenv install --dev
                pipenv run playwright install

            - name: Connect to PostgreSQL
              run: |
                python psql_setup.py
            
            - name: Test with pytest
              run: |
                export CREATOR_PASS="${{ secrets.CREATOR_PASS }}"
                export CREATOR_EMAIL="${{ secrets.CREATOR_EMAIL }}"
                pipenv run pytest